In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html


In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0, 1, 2]

tensor(9)

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensor -> https://pytorch.org/docs/stable/generated/torch.rand.html


In [17]:
# Create a random tensor of shape/size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4545, 0.4626, 0.7558, 0.4891],
        [0.3114, 0.9382, 0.4671, 0.1161],
        [0.5770, 0.1330, 0.2955, 0.4884]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [20]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [27]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is tensor (e.g. float32)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [31]:
torch.tensor([3, 4, 5],
             dtype=torch.complex32,
             requires_grad=True)

<ipython-input-31-3fa3d54e6494>:1: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at ../aten/src/ATen/EmptyTensor.cpp:41.)
  torch.tensor([3, 4, 5],


tensor([3.+0.j, 4.+0.j, 5.+0.j], dtype=torch.complex32, requires_grad=True)

In [32]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [33]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors attributes

1. Tensors not right datatype - to do get datatyoe from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [34]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2742, 0.8734, 0.8794, 0.4583],
        [0.7158, 0.3365, 0.7374, 0.6698],
        [0.2590, 0.9708, 0.9249, 0.9103]])

In [35]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.2742, 0.8734, 0.8794, 0.4583],
        [0.7158, 0.3365, 0.7374, 0.6698],
        [0.2590, 0.9708, 0.9249, 0.9103]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [36]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [37]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [38]:
tensor

tensor([1, 2, 3])

In [39]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [40]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [41]:
tensor / 3

tensor([0.3333, 0.6667, 1.0000])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)


In [42]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [43]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [44]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [45]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
#print(value)

CPU times: user 677 µs, sys: 0 ns, total: 677 µs
Wall time: 4.43 ms


In [46]:
%%time
result = torch.matmul(tensor, tensor)
#print(result)

CPU times: user 115 µs, sys: 0 ns, total: 115 µs
Wall time: 120 µs


In [47]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.8096, 0.4600, 1.0858],
        [0.8143, 0.4072, 0.9748],
        [0.5907, 0.3298, 0.7798]])

### One of the most common errors in deep learning: shape errors

In [48]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm(tensor_A, tensor_B) # tensor.mm is the same as torch.matmul
#torch.matmul(tensor_A, tensor_B)

To fix our tensor shape issues, we can manipulate of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [49]:
tensor_B, tensor_B.T

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [50]:
tensor_B.T.shape

torch.Size([2, 3])

In [51]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [52]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [53]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [54]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [55]:
# Find the mean - note: the torch.mean() function requires a tensor of float or complex dtypes
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [56]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [57]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [58]:
x.argmin()

tensor(0)

In [59]:
x[0]

tensor(0)

In [60]:
x.argmax()

tensor(9)

In [61]:
x[9]

tensor(90)

## Reshaping, stacking squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [62]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [63]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [64]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
# Changing z changes x, because a view of a tansor shares the same memory as the original input
z[:, 0] = 5
z , x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [66]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [67]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [68]:
# torch.unsqueeze() - adds a isngle dimension to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [69]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)
x_permuted.shape

torch.Size([3, 224, 224])

In [70]:
x_original[0, 1, 2] = 999

In [71]:
x_permuted[2, 0, 1]

tensor(999.)

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy


In [72]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [73]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [74]:
x[0, 0]

tensor([1, 2, 3])

In [75]:
x[0, 1, 2]

tensor(6)

In [76]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [77]:
x[:, 1, 1], x[0, 1, 1]

(tensor([5]), tensor(5))

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`


In [78]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: default numpy array dtype: float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [79]:
array.dtype

dtype('float64')

In [80]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [81]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [82]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [83]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neral network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural network and PyTorch comes to the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [86]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4716, 0.2576, 0.7480, 0.0452],
        [0.2167, 0.5829, 0.0968, 0.5802],
        [0.6104, 0.3527, 0.9770, 0.0419]])
tensor([[0.8808, 0.2965, 0.9023, 0.1457],
        [0.3831, 0.7001, 0.3348, 0.8021],
        [0.0874, 0.6604, 0.1879, 0.4822]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [103]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.5014, 0.3139, 0.4654, 0.1612],
        [0.1568, 0.2083, 0.3289, 0.1054],
        [0.9192, 0.4008, 0.9302, 0.6558]])
tensor([[0.0766, 0.8460, 0.3624, 0.3083],
        [0.0850, 0.0029, 0.6431, 0.3908],
        [0.6947, 0.0897, 0.8712, 0.1330]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA = NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good)

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options...
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them.

For 2, 3 PyTorch + GPU drivers (CUDA) takes little bit of setting up, to do this, refer to PyTorch setup documentation.


In [1]:
!nvidia-smi

Sat May 25 13:26:37 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [2]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is beacause using a GPU results in faster computations.


In [5]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [7]:
# If tensor is on GPU, can't transform it to NumPy
#tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [8]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercises & Extra-curriculum

https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises
